#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Adapted dreamwalk_script_09.py for the AOP Rare Disease KG.
(0.9 STRING score cutoff workflow)

Changes from original:
  - Removed save_sim_graph / drug similarity (no drugs in this KG)
  - sim_netf switched from hierarchy.csv → dis_sim.tsv
  - find_candidates → find_aop_candidates (Disease→AOP, not Drug→Disease)
  - Output path updated to aop results folder
"""

# Set path
import os
from pathlib import Path
import numpy as np
import pandas as pd
import pickle

path = Path(__file__).resolve().parent
os.chdir(path)

import DREAMwalk.generate_files as gen
import DREAMwalk.generate_dis_sim as dis_gen
from DREAMwalk.generate_embeddings import save_embedding_files
from DREAMwalk.predict_associations import predict_dda


# ── GENERATE FILES ────────────────────────────────────────────────────────────
kg_data = pd.read_csv('preprocessed_graph.csv')
gen.generate_files(kg_data)

dis_gen.save_dis_sim('preprocessed_graph.csv', 'dis_sim.tsv')

# ── ALGORITHM ─────────────────────────────────────────────────────────────────
# Drug similarity removed — no drugs in this KG
# Similarity graph = disease similarity only
dis_sim = pd.read_csv('dis_sim.tsv', sep='\t', header=None)
dis_sim[4] = range(len(dis_sim))
dis_sim.to_csv('similarity_graph.txt', sep='\t', index=False, header=False)

# Generate node embeddings by teleport-guided random walk
# sim_netf = dis_sim.tsv (was hierarchy.csv in original — ATC drug hierarchy)
networkf   = 'graph.txt'
nodetypef  = 'nodetypes.tsv'
embeddingf = 'embedding_file09.pkl'
simf       = 'dis_sim.tsv'

save_embedding_files(netf=networkf, sim_netf=simf, outputf=embeddingf,
                     nodetypef=nodetypef, tp_factor=0.3)

# Predict disease–AOP associations
# Pair file: all disease × AOP combinations (generated by dreamwalk_script_aop.py)
pairf      = 'aop_pair_files/disease_aop_pairs.tsv'
modelf     = 'results/clf10.pkl'
embeddingf = 'embedding_file09.pkl'

predict_dda(embeddingf=embeddingf, pairf=pairf, modelf=modelf)



# ── FIND AOP CANDIDATES FOR A QUERY DISEASE ───────────────────────────────────
def find_aop_candidates(kgfile, embeddingf, model_folder,
                        query_disease, candidates_count=20):
    """
    Adapted from find_candidates() — returns top-scored AOP events
    for a given query disease using node embeddings and all trained
    classifiers in model_folder (averaged).
    """
    kg = pd.read_csv(kgfile, low_memory=False)
    nodes = kg[kg['_start'].isna()]
    aop_nodes = nodes[nodes['_labels'] == ':AOP']['id'].dropna().unique()

    query_pairs = pd.DataFrame({
        'disease': query_disease,
        'aop'    : aop_nodes,
        'label'  : 0,
    })
    tmp_pairf = '_tmp_query_pairs.tsv'
    query_pairs.to_csv(tmp_pairf, sep='\t', index=False, header=False)

    clf_files = sorted(Path(model_folder).glob('clf*.pkl'))
    if not clf_files:
        print("No trained model found in results/ — cannot score candidates.")
        os.remove(tmp_pairf)
        return pd.DataFrame()

    all_scores = []
    for clf_path in clf_files:
        s = predict_dda(embeddingf=embeddingf, pairf=tmp_pairf,
                        modelf=str(clf_path))
        all_scores.append(s)
    os.remove(tmp_pairf)

    query_pairs['score'] = np.mean(all_scores, axis=0)
    return (query_pairs
            .sort_values('score', ascending=False)
            .head(candidates_count)
            .reset_index(drop=True))


embeddingf   = 'embedding_file09.pkl'
model_folder = 'results'
kgfile       = 'preprocessed_graph.csv'
query_disease = 'C0000000'   # ← replace with your UMLS CUI of interest

os.makedirs('results', exist_ok=True)

find_aop_candidates(kgfile, embeddingf, model_folder,
                    query_disease, candidates_count=20)

results1 = find_aop_candidates(kgfile, embeddingf, model_folder,
                                query_disease, candidates_count=400)
results1.to_csv('results/aop_results_0.9.csv', index=False)
